# Generated by Django 4.1.7 on 2024-03-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tournament', '0002_alter_tournament_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_organizer',
            field=models.CharField(default='No Organizer', max_length=32),
        ),
    ]
