# Generated by Django 3.2 on 2024-04-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tournament', '0003_tournament_tournament_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(default='Upcoming', max_length=10),
        ),
    ]
