# Generated by Django 3.2 on 2024-03-03 06:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games_list', '0002_auto_20240228_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('dateStart', models.DateTimeField(default=datetime.datetime.now)),
                ('dateEnd', models.DateTimeField(default=datetime.datetime.now)),
                ('location', models.CharField(max_length=100)),
                ('tournyFormat', models.CharField(choices=[('se', 'Single Elimination'), ('de', 'Double Elimination')], default='se', max_length=100)),
                ('details', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_list.game')),
            ],
        ),
    ]
