# Generated by Django 3.2 on 2024-03-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='prizePool',
            field=models.TextField(null=True),
        ),
    ]
