# Generated by Django 3.2 on 2024-03-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_list', '0002_tournament_prizepool'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tier',
            field=models.CharField(choices=[('S', 'S Tier'), ('A', 'A Tier'), ('B', 'B Tier'), ('C', 'C Tier'), ('D', 'D Tier')], default='A', max_length=100),
        ),
    ]
