# Generated by Django 4.1.7 on 2024-03-05 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_list', '0002_auto_20240228_1046'),
        ('tournaments_list', '0003_tournament_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='games_list.game'),
        ),
    ]
