# Generated by Django 5.0.3 on 2024-03-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JoinTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountUser', models.CharField(default='no account', max_length=32)),
                ('ign', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('country', models.CharField(max_length=64)),
            ],
        ),
    ]
