# Generated by Django 5.0.3 on 2024-03-26 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_tournament', '0001_initial'),
        ('register', '0006_account_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountUser', models.CharField(default='no account', max_length=32)),
                ('ign', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('country', models.CharField(max_length=64)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.account')),
            ],
        ),
        migrations.DeleteModel(
            name='JoinTournament',
        ),
    ]
