# Generated by Django 5.0.3 on 2024-04-19 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tournament', '0004_tournament_status'),
        ('join_tournament', '0002_tournamentplayer_delete_jointournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='application_status',
            field=models.CharField(default='Pending', max_length=25),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='ranking',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='create_tournament.tournament'),
        ),
    ]
