# Generated by Django 5.0.3 on 2024-04-19 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tournament', '0004_tournament_status'),
        ('join_tournament', '0003_tournamentplayer_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentplayer',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_tournament.tournament'),
        ),
    ]
