# Generated by Django 4.1.7 on 2024-04-18 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0006_account_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications1', models.BooleanField(default=False)),
                ('notifications2', models.BooleanField(default=False)),
                ('notifications3', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.account')),
            ],
        ),
    ]
