# Generated by Django 4.1.7 on 2024-04-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='notifications3',
        ),
    ]
