# Generated by Django 4.1.7 on 2024-04-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_page', '0002_remove_notifications_notifications3'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
