# Generated by Django 4.1.7 on 2024-04-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_page', '0004_remove_notifications_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='notifications2',
        ),
    ]
