# Generated by Django 4.1.7 on 2024-04-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_page', '0006_notifications_notifications2'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notifications3',
            field=models.BooleanField(default=False),
        ),
    ]
