# Generated by Django 3.2 on 2024-04-22 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('create_tournament', '0004_tournament_status'),
        ('join_tournament', '0004_alter_tournamentplayer_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=15)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_tournament.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchNumber', models.IntegerField()),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='tournament_details.bracket')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInMatchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerNumber', models.IntegerField()),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament_details.matchup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='join_tournament.tournamentplayer')),
            ],
        ),
    ]
