# Generated by Django 3.2 on 2024-04-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='resultConfirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchup',
            name='status',
            field=models.CharField(default='Upcoming', max_length=10),
        ),
        migrations.AddField(
            model_name='playerinmatchup',
            name='isWinner',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='playerinmatchup',
            name='score',
            field=models.IntegerField(default=-1),
        ),
    ]
