# Generated by Django 4.2.10 on 2024-02-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('isOrganizer', models.BooleanField(default=False)),
            ],
        ),
    ]
