# Generated by Django 4.2.10 on 2024-03-04 15:47

from django.db import migrations, models
import django.db.models.deletion
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.account')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=32)),
                ('contact_number', models.CharField(max_length=15, validators=[register.models.validate_contact_number])),
                ('past_experience', models.TextField()),
                ('additional_comments', models.TextField()),
            ],
            bases=('register.account',),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
