# Generated by Django 4.2.10 on 2024-03-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_organizeraccount_alter_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizeraccount',
            name='additional_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizeraccount',
            name='past_experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
